reproio/wrapbox

lib/wrapbox/runner/ecs.rb

`client.run_task` で利用するcluster引数を `cl` に統一しました。

Fix cluster argument to use cl variable

---

lib/wrapbox/runner/ecs.rb

Just print contaier stopped reason.
When caused some error (e.g. ExecutionFailure), that use task stopped reason for printing error message but it's just useless for developers, we should know about inner situation like below:
* current output in master branch:
```
master* $ wrapbox ecs run_cmd 'dd if=/dev/zero of=tempfile bs=1G count=6' -f config.yml --launch_retry=1
D, [2017-05-01T12:25:10.036054 #98966] DEBUG -- : Create Task: arn:aws:ecs:ap-northeast-1:287195237987:task/3bc6d4b0-dd2e-4df5-9a93-e166383cbd11
D, [2017-05-01T12:25:15.119290 #98966] DEBUG -- : Launch Task: arn:aws:ecs:ap-northeast-1:287195237987:task/3bc6d4b0-dd2e-4df5-9a93-e166383cbd11
D, [2017-05-01T12:25:15.136324 #98966] DEBUG -- : Stop Task: arn:aws:ecs:ap-northeast-1:287195237987:task/3bc6d4b0-dd2e-4df5-9a93-e166383cb …
```

Print container stopped reason

---

lib/wrapbox/runner/ecs.rb

Print error details when LaunchFailure occured.
This PR need to merge after https://github.com/reproio/wrapbox/pull/2.
Some errors(e.g. LaunchFailure) print nothing. so just I want to know the details like below:
(command has no meaning, just I need to cause LaunchFailure)
* current output on master branch:
```
master* $ wrapbox ecs run_cmd 'cd /var && ls .' -f config.yml --launch_retry=1
D, [2017-05-01T15:02:01.018020 #8996] DEBUG -- : Create Task: arn:aws:ecs:ap-northeast-1:287195237987:task/c133dee9-904c-449d-8c44-1039fb693cab
D, [2017-05-01T15:02:06.099249 #8996] DEBUG -- : Retry Create Task after 1 sec
D, [2017-05-01T15:02:07.156958 #8996] DEBUG -- : Create Task: arn:aws:ecs:ap-northeast-1:287195237987:task/ce5135c9-0164-49d3-8a0b-31cc337e5f6e …
```

Print error details on LaunchFailure occured

---

lib/wrapbox/runner/ecs.rb

`fetch_task_status` returns a container status that match `tash_definition_name`, not assignment.

Fix to fetch task status

---

README.md
lib/wrapbox/runner/docker.rb
lib/wrapbox/runner/ecs.rb

I've introduce `WRAPBOX_CMD_INDEX` environment variable.
It is useful for distinguishing logs from each command as I describe in READM.md.

Introduce WRAPBOX_CMD_INDEX

---

lib/wrapbox/runner/ecs.rb

This PR will fix errors like below:
```
wrapbox-1553b56b1c94/lib/wrapbox/runner/ecs.rb:232:in `rescue in wait_task_stopped': undefined local variable or method `cl' for #<Wrapbox::Runner::Ecs:0x00000002d99700> (NameError)
from /home/circleci/repro/vendor/bundle/ruby/2.4.0/bundler/gems/wrapbox-1553b56b1c94/lib/wrapbox/runner/ecs.rb:222:in `wait_task_stopped'
from /home/circleci/repro/vendor/bundle/ruby/2.4.0/bundler/gems/wrapbox-1553b56b1c94/lib/wrapbox/runner/ecs.rb:105:in `run_task'
from /home/circleci/repro/vendor/bundle/ruby/2.4.0/bundler/gems/wrapbox-1553b56b1c94/lib/wrapbox/runner/ecs.rb:84:in `block (2 levels) in run_cmd'
```

Fix "undefined local variable" error

---

lib/wrapbox/configuration.rb
lib/wrapbox/runner/docker.rb
lib/wrapbox/runner/ecs.rb
wrapbox.gemspec

- deprecate `additional_container_definitions`, Use `container_definitions`
- Use first of `container_definitions` as main container
- Support new ECS parameters
- volumes
- placement_constraints
- placement_strategies
- task level cpu, memory constraints
- network_mode, network_configuration
- requires_compatibilities, launch_type

Support ECS new features and refactor configuration

---

lib/wrapbox/runner/ecs.rb

I use environment variables in syslog tags
to separate logs of each task, so it is convenient
to override environments of all containers.

Override environments of all containers

---

lib/wrapbox/log_fetcher/papertrail.rb

I fixed to raise NoMethodError when failed on `Wrapbox::Runner::Ecs#create_task`.
https://github.com/reproio/wrapbox/blob/15d46b0085180e42f11e6e697a2e38eab5ab95a5/lib/wrapbox/runner/ecs.rb#L160-L161

Fix NoMethodError on #stop before #run

---

lib/wrapbox/runner/ecs.rb

How about logging failures message in run_task?
See also https://docs.aws.amazon.com/sdkforruby/api/Aws/ECS/Client.html#run_task-instance_method

Show arn and resoure of failures

---

lib/wrapbox/log_fetcher/papertrail.rb
lib/wrapbox/runner/docker.rb
lib/wrapbox/runner/ecs.rb
spec/config.yml
spec/wrapbox_spec.rb

This patch support signal propagation to containers.
If user send signal to wrapbox command (TERM, INT, QUIT and so),
wrapbox propagates signal to ECS or docker.
To specify signal type on ECS is not supported. And so if use ECS, wrapbox kicks `stop_task` API.

Support SIGNAL handling for ECS Task stopping

---

lib/wrapbox/runner/ecs.rb
wrapbox.gemspec

I want to avoid installing unnecessary gems.
aws-sdk-v3 support modularized gems.
<details>
<summary>before</summary>
```
Fetching gem metadata from https://rubygems.org/....................
Resolving dependencies........
Using concurrent-ruby 1.0.5
Using minitest 5.11.3
Using thread_safe 0.3.6
Using aws-partitions 1.63.0
Using aws-sigv4 1.0.2
Using jmespath 1.3.1
Using aws-sigv2 1.0.1
Using bundler 1.16.0
Using excon 0.60.0
Using i18n 0.9.5
Using tzinfo 1.2.5
Using aws-sdk-core 3.15.0
Using multi_json 1.13.1
Using thor 0.20.0
Using activesupport 5.1.5
Using aws-sdk-acm 1.3.0
Using aws-sdk-alexaforbusiness 1.1.0
Using aws-sdk-apigateway 1.9.0
Using aws-sdk-applicationautoscaling 1.7.0
Using aws-sdk-applicationdiscoveryservice 1.1.0
Using aws-sdk-appstream 1.5.0
Using aws-sdk-appsync 1.1.0 …
```

Use modularized aws-sdk And Stop supporting aws-sdk-v2

---

README.md

Fix README according to the following changes:
https://github.com/reproio/wrapbox/commit/08dea421bc259844d242608d81fbda336a0d849c
Please review. 🙏

Fix README: rm -> keep_container

---

lib/wrapbox/configuration.rb
lib/wrapbox/runner/ecs.rb

Fargate needs `execution_role_arn` on task_definition
Sample yml:
```
default:
cluster: sample-cluster
region: ap-northeast-1
task_role_arn: 'arn:aws:iam::11111111111111:role/taskRole'
execution_role_arn: 'arn:aws:iam::11111111111:role/ecsTaskExecutionRole'
launch_type: 'FARGATE'
requires_compatibilities: ['FARGATE']
network_mode: 'awsvpc'
network_configuration:
awsvpc_configuration:
subnets: ["subnet-xxxxxxxx"]
security_groups: ["sg-xxxxxxxx"]
assign_public_ip: 'ENABLED'
cpu: 1024
memory: 2048
container_definitions:
...
```

Support Fargate

---

lib/wrapbox/runner/ecs.rb

This PR is for handling Throttling execption with many api calls.
Throttiling execption happens if many tasks are launched with pararell. e.g.
```
require 'wrapbox/cli'
Wrapbox::Cli.start(%w[ecs run_cmd -f config.yml --launch_type FARGATE] + ["ls"]*50)
```

rescue Throttling Exception

---

README.md
lib/wrapbox/configuration.rb
lib/wrapbox/runner/ecs.rb

This PR supports [tagging ECS resources](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-using-tags.html).
You can run tasks with tags using a configuration like below:
```yaml
default:
cluster: default
runner: ecs
region: ap-northeast-1
cpu: 256
memory: 256
tags:
- key: Foo
value: "1"
enable_ecs_managed_tags: true
propagate_tags: TASK_DEFINITION
container_definitions:
- image: ubuntu
essential: true
```
I want this feature because we can restrict permissions using tags like below:
```
{
"Version": "2012-10-17",
"Statement": [
{
"Effect": "Allow",
"Action": "ecs:DescribeTasks",
"Resource": "*",
"Condition": {
"StringEquals": {
"ecs:ResourceTag/Foo": "1"
}
}
}
]
}
```

Support tagging ECS resources

---

README.md
lib/wrapbox/configuration.rb
lib/wrapbox/runner/ecs.rb
lib/wrapbox/runner/ecs/instance_manager.rb
spec/config.yml
spec/spec_helper.rb
spec/wrapbox_spec.rb
wrapbox.gemspec

It takes much time to launch Fargate tasks and the performance of Fargate is low, so this feature can be used as an alternative to Fargate.

 Add a feature to launch a new instance per task like Fargate

---

README.md
lib/wrapbox/runner/ecs/instance_manager.rb
spec/config.yml

This is useful for adding task information to instances and makes it easier to manage them.
For example, I want to terminate the instances a wrapbox fails to terminate when the process is killed.

Add tag_specifications option to launch_instances config

---

README.md
lib/wrapbox/configuration.rb
lib/wrapbox/runner/docker.rb
lib/wrapbox/runner/ecs.rb
lib/wrapbox/runner/ecs/instance_manager.rb
lib/wrapbox/runner/ecs/task_waiter.rb
spec/wrapbox_spec.rb

`Runner::Ecs` calls `describe_tasks` in `wait_task_stopped` as many as its tasks, so sometimes causes `Aws::ECS::Errors::ThrottlingException`.

Reduce describe_tasks calls

---

lib/wrapbox/runner/ecs/task_waiter.rb
spec/wrapbox/runner/ecs/task_waiter_spec.rb

`@task_arn_to_described_result` of `Wrapbox::Runner::Ecs::TaskWaiter` won't be empty if an error is raised in `wait_task_running` or `wait_task_stopped`.
This PR fixes it.

Fix a bug that describes certain tasks forever

---

lib/wrapbox/runner/ecs.rb

This PR resolves https://github.com/reproio/wrapbox/issues/32 again.
Although I changed the code to retry run_task on the errors by https://github.com/reproio/wrapbox/pull/33, the error message recently seemed to change.
cf. https://github.com/reproio/wrapbox/issues/32#issuecomment-651343018

Retry to run the task on request limit exceeded errors

---

lib/wrapbox/runner/ecs.rb

Same as title.
Although wrapbox calls register_task_definition only once, Aws::ECS::Errors::ThrottlingException occurs as below if another process calls it many times:
```
Aws::ECS::Errors::ThrottlingException: Rate exceeded
--
/opt/ruby/lib/ruby/gems/2.5.0/gems/aws-sdk-core-3.89.1/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call'
/opt/ruby/lib/ruby/gems/2.5.0/gems/aws-sdk-core-3.89.1/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'
/opt/ruby/lib/ruby/gems/2.5.0/gems/aws-sdk-core-3.89.1/lib/aws-sdk-core/plugins/idempotency_token.rb:17:in `call'
/opt/ruby/lib/ruby/gems/2.5.0/gems/aws-sdk-core-3.89.1/lib/aws-sdk-core/plugins/param_converter.rb:24:in `call'
/opt/ruby/lib/ruby/gems/2.5.0/gems/aws-sdk-core-3.89.1/lib/aws-sdk-core/plugins/response_paging.rb:10:in …
```

Retry register_task_definition on ThrottlingException

---

wrapbox.gemspec

that is separated from bundled gem from ruby 2.7

Add the dependency of thwait gem

---

lib/wrapbox/runner/ecs.rb

I fixed splatting log_fetcher options in deploying ECS for  ruby-3.0 kwargs.
```
--
15:59:49 |   |   | 2021-08-16 06:59:47.505 dev_staging/wrapbox_batch_dev_staging/7ee7af828b29422cb61cec8ddef413d0 I, [2021-08-16T06:59:47.505451 #1]  INFO -- : Start Workflow::CopyConversionFactsDayAsTotalAccess
15:59:49 |   |   | 2021-08-16 06:59:47.776 dev_staging/wrapbox_batch_dev_staging/7ee7af828b29422cb61cec8ddef413d0 #<Thread:0x00007f2d8c64a5f8 /app/workflows/jobs/copy_from_gcs_to_s3.rb:37 run> terminated with exception (report_on_exception is true):
15:59:49 |   |   | 2021-08-16 06:59:47.776 dev_staging/wrapbox_batch_dev_staging/7ee7af828b29422cb61cec8ddef413d0 /app/vendor/bundle/ruby/3.0.0/bundler/gems/wrapbox-ee3c1ddbf84a/lib/wrapbox/log_fetcher.rb:8:in `new': wrong number of arguments (given 2, …
```

unexpected hash in ruby-3.0

---

lib/wrapbox/log_fetcher/awslogs.rb

The error is sometimes raised but doesn't affect the main feature, so we can ignore it.
Here is reproducible code:
```ruby
require 'aws-sdk-ecs'
require 'wrapbox'
require 'wrapbox/log_fetcher/awslogs'
task = Aws::ECS::Client.new.describe_tasks(tasks: [ENV.fetch('TASK_ID')]).tasks.first
fetcher = Wrapbox::LogFetcher::Awslogs.new(log_group: ENV.fetch('LOG_GROUP'), log_stream_prefix: ENV.fetch('LOG_STREAM_PREFIX'))
Array.new(1000) do |i|
sleep i / 10000.0
fetcher.run(task: task)
end.each(&:join)
```
```
% git rev-parse HEAD
f0c03dfffc502ce30bdb0aa1e78c41beb40c032b
% LOG_GROUP=/ecs/hello-loop-fargate TASK_ID=c0abddf2a0024c62bbf01f1dbe1a01f6 LOG_STREAM_PREFIX=ecs ruby -Ilib /path/to/script.rb >/dev/null
#<Thread:0x00007fd277de3838 /Users/arabiki/ghq/src/github.com/reproio/wrapbox/lib/wrapbox/lo …
```

Ignore throttling exception in Wrapbox::LogFetcher::Awslogs

---

lib/wrapbox/log_fetcher/awslogs.rb
spec/config.yml

The PR https://github.com/reproio/wrapbox/pull/42 made it occur when the log stream hasn't been created yet, that is, the task hasn't started yet, so I fixed it.

Ignore Aws::CloudWatchLogs::Errors::ResourceNotFoundException

---

lib/wrapbox/log_fetcher/awslogs.rb

It seems that task.contaienrs is empty if capacity_provider_strategy is specified and there is no remaining capacity like below, and if taskcontainers is empty, the above error occurs:
```
=> #<struct Aws::ECS::Types::Task
-- snip --
containers=[],
cpu="2038",
created_at=2022-08-15 14:20:12 1228931/4194304 +0900,
desired_status="RUNNING",
enable_execute_command=false,
execution_stopped_at=nil,
-- snip --
last_status="PROVISIONING",
launch_type="EC2",
memory="3000",
-- snip --
```
So, this PR fixes the error by fetching the task until it has containers like below:
```
W, [2022-08-15T14:41:23.325608 #66226]  WARN -- : The task has no containers, so fetch it again
W, [2022-08-15T14:41:33.375656 #66226]  WARN -- : The task has no containers, so fetch it again
-- snip --
W, …
```

Fix "validation error detected: Value '[]' at 'logStreamNames' ..."

---

.github/workflows/main.yml
lib/wrapbox/runner/ecs.rb

Add double splat to Hash.
See https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/

Support Ruby3

---

.github/workflows/main.yml
lib/wrapbox/config_repository.rb
spec/config.yml

Psych 4 included in Ruby 3.1 complains when using aliases in yaml files.
This PR adds `aliases: true` option to load yaml as before.
ref: https://bugs.ruby-lang.org/issues/17866

Fix yaml loading for Ruby 3.1

---

lib/wrapbox/configuration.rb

I met the following error if use with ActiveSupport 7.1.x.
```console
❯ bundle exec exe/wrapbox --help
bundler: failed to load command: exe/wrapbox (exe/wrapbox)
/home/kenji/.local/share/rtx/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.2/lib/active_support/core_ext/array/conversions.rb:108:in `<class:Array>': undefined method `deprecator' for ActiveSupport:Module (NoMethodError)
deprecate to_default_s: :to_s, deprecator: ActiveSupport.deprecator
^^^^^^^^^^^
```
I've added `require "active_support"` before load other active_support libraries to fix the issue.
See
- https://guides.rubyonrails.org/active_support_core_extensions.html#stand-alone-active-support
- https://github.com/rails/rails/issues/49495

Support ActiveSupport 7.1.x
